version: '3'

services:
  sftpgo:
    image: drakkan/sftpgo:alpine-slim
    container_name: sftpgo
    environment:
      - "SFTPGO_FTPD__BINDINGS__0__PORT=2121"
      - "SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP=172.19.0.5"
    volumes:
      - "${DATA_PATH}/sftpgo:/var/lib/sftpgo"
      - "${DATA_PATH}/files:/srv/sftpgo/data"
    networks:
      default:
        ipv4_address: 172.19.0.20
    ports:
      - 2121:2121
      - 50000-50100:50000-50100

networks:
  default:
    name: lsio
    external: true