version: '3.8'

services:

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    environment:
      - "GF_SERVER_ROOT_URL=https://grafana.chst.dev"
      - "GF_INSTALL_PLUGINS=grafana-clock-panel"
    ports:
      - '3000:3000'
    volumes:
      - "${DATA_PATH}/grafana:/var/lib/grafana"