version: '3.8'

services:

  gitea:
    image: gitea/gitea:1.21.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - "${DATA_PATH}/gitea:/data"
    ports:
      - "222:22"
    env_file:
      - ../envs/base.env

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - "${DATA_PATH}/homeassistant:/config"
    restart: unless-stopped
    privileged: true
    network_mode: host

networks:
  default:
    name: lsio
    external: true