version: "2.1"

services:

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:
      - "${DATA_PATH}/qbittorrent:/config"
      - "${DATA_PATH}/files/downloads:/downloads"
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    env_file:
      - ../envs/base.env

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "${DATA_PATH}/radarr:/config"
      - "${DATA_PATH}/files/movies:/movies"
      - "${DATA_PATH}/files/downloads:/downloads"
    restart: unless-stopped
    env_file:
      - ../envs/base.env

networks:
  default:
    name: lsio
    external: true