version: "2.2"

services:

  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: "portainer"
    command: "-H unix:///var/run/docker.sock"
    environment:
      - "VIRTUAL_HOST=portainer.chst.dev"
      - "VIRTUAL_PORT=9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DATA_PATH}/portainer:/data"
    restart: "always"
    env_file:
      - ../envs/base.env

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    user: 1000:1000
    volumes:
      - ${DATA_PATH}/ntfy:/etc/ntfy
    ports:
      - 8088:8088
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://ntfy:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
    env_file:
      - ../envs/base.env

networks:
  default:
    name: lsio
    external: true
