version: "3.5"

services:

  diun:
    image: crazymax/diun:latest
    command: serve
    volumes:
      - "${DATA_PATH}/diun:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "DIUN_WATCH_WORKERS=5"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_NOTIF_NTFY_ENDPOINT=https://ntfy.chst.dev"
      - "DIUN_NOTIF_NTFY_TOPIC=manage"
      - "DIUN_NOTIF_NTFY_TAGS=loadspeaker"
      - "DIUN_NOTIF_NTFY_TIMEOUT=10s"
    labels:
      - "diun.enable=true"
    restart: always
    env_file:
      - ../envs/base.env

networks:
  default:
    name: lsio
    external: true
