version: "2.2"

services:

  swag:
    image: "lscr.io/linuxserver/swag"
    container_name: "swag"
    cap_add:
      - "NET_ADMIN"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${TIMEZONE}"
      - "URL=chst.dev"
      - "SUBDOMAINS=www,"
      - "VALIDATION=http"
      - "CERTPROVIDER=zerossl"
      - "EMAIL=griffin@chst.dev"
      - "DNSPLUGIN=cloudflare"
      - "ONLY_SUBDOMAINS=true"
      - "STAGING=false"
    volumes:
      - "${DATA_PATH}/swag:/config"
    ports:
      - 443:443
      - 80:80
    restart: "unless-stopped"
    env_file:
      - ../envs/base.env

  # authelia:
  #   container_name: "authelia"
  #   image: "authelia/authelia"
  #   expose:
  #     - 9091
  #   volumes:
  #     - "/home/hichi/data/authelia:/config"
  #   environment:
  #     - "TZ=America/Sao_Paulo"
  #   restart: "unless-stopped"

networks:
  default:
    name: lsio
    external: true
