version: "2.2"

services:

  n8n:
    image: "n8nio/n8n:latest"
    container_name: "n8n"
    environment:
      - "TZ=${TZ}"
      - "N8N_HOST=n8n.orochi.chst.dev"
      - "N8N_PROTOCOL=https"
      - "N8N_PORT=5678"
      - "WEBHOOK_URL=https://n8n.orochi.chst.dev/"
      - "N8N_EDITOR_BASE_URL=https://n8n.orochi.chst.dev/"
      - "N8N_DIAGNOSTICS_ENABLED=false"
      - "N8N_PERSONALIZATION_ENABLED=false"
      - "N8N_SECURE_COOKIE=true"
      - "VIRTUAL_HOST=n8n.orochi.chst.dev"
      - "VIRTUAL_PORT=5678"
    volumes:
      - "${DATA_PATH}/n8n:/home/node/.n8n"
    restart: "unless-stopped"
    networks:
      default:
        ipv4_address: "${LSIO_IP}.85"
    env_file:
      - ../envs/base.env

  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: "portainer"
    command: "-H unix:///var/run/docker.sock"
    environment:
      - "VIRTUAL_HOST=portainer.${BASE_DOMAIN}"
      - "VIRTUAL_PORT=9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DATA_PATH}/portainer:/data"
    restart: "always"
    #ports:
    #  - 9000:9000 # Debug
    env_file:
      - ../envs/base.env

networks:
  default:
    name: lsio
    external: true
