version: "3.5"

services:

  diun:
    image: crazymax/diun:latest
    container_name: "diun"
    command: serve
    volumes:
      - "${DATA_PATH}/diun:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "DIUN_WATCH_WORKERS=5"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_WATCH_RUNONSTARTUP=true"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_NTFY_ENDPOINT=${NTFY_INTERNAL_ADDRESS}"
      - "DIUN_NOTIF_NTFY_TOPIC=manage"
      - "DIUN_NOTIF_NTFY_TAGS=loudspeaker"
      - "DIUN_NOTIF_NTFY_TIMEOUT=10s"
    labels:
      - "diun.enable=true"
    restart: always
    env_file:
      - ../envs/base.env
      - ../envs/ntfy.env

networks:
  default:
    name: lsio
    external: true
