version: '3.8'

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped
    volumes:
      - "${DATA_PATH}/prometheus:/etc/prometheus"
    env_file:
      - ../envs/base.env
    extra_hosts:
      - "host.docker.internal=host-gateway"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    volumes:
      - "${DATA_PATH}/grafana:/etc/grafana/provisioning/datasources"
    env_file:
      - ../envs/base.env
      - ../envs/grafana.env

networks:
  default:
    name: lsio
    external: true