services:

  uptime-kuma:
    image: "louislam/uptime-kuma:1"
    container_name: "uptime-kuma"
    environment:
      - "TZ=${TZ}"
      - "VIRTUAL_HOST=uptime.${BASE_DOMAIN}"
      - "VIRTUAL_PORT=3001"
    volumes:
      - "${DATA_PATH}/uptime-kuma:/app/data"
    restart: "unless-stopped"
    #ports:
    #  - "3001:3001" # Debug
    env_file:
      - ../envs/base.env

  # scrutiny removed: not useful in current virtualized storage setup

networks:
  default:
    name: lsio
    external: true
