version: "2.2"

services:

  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: "portainer"
    command: "-H unix:///var/run/docker.sock"
    environment:
      - "VIRTUAL_HOST=portainer.chst.dev"
      - "VIRTUAL_PORT=9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DATA_PATH}/portainer:/data"
    restart: "always"
    env_file:
      - ../envs/base.env

networks:
  default:
    name: lsio
    external: true
