services:
  curlbox:
    image: curlimages/curl:latest
    container_name: curlbox
    command: ["sh", "-c", "sleep infinity"]
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    networks:
      - default

networks:
  default:
    name: lsio
    external: true
