version: "3"

services:

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    expose:
      - "8000"
    volumes:
      - "${DATA_PATH}/paperless:/usr/src/paperless/data"
      - "${DATA_PATH}/paperless:/usr/src/paperless/media"
      - "${DATA_PATH}/files/serviceuser/export:/usr/src/paperless/export"
      - "${SHARES_PATH}/home/lionswrath/docs-topic-upload:/usr/src/paperless/consume"
    restart: unless-stopped
    env_file:
      - ../envs/base.env
      - ../envs/db_paperless.env
    environment:
      - PAPERLESS_URL=https://paperless.orochi.chst.dev
      - PAPERLESS_CSRF_TRUSTED_ORIGINS=https://paperless.orochi.chst.dev
      - PAPERLESS_ALLOWED_HOSTS=paperless.orochi.chst.dev,paperless,localhost,127.0.0.1
      - PAPERLESS_OCR_LANGUAGE=por+eng
      - PAPERLESS_OCR_LANGUAGES=por
      - PAPERLESS_OCR_MODE=skip
      - PAPERLESS_OCR_CLEAN=clean
      - PAPERLESS_OCR_DESKEW=1
      - PAPERLESS_OCR_ROTATE_PAGES=1
      - PAPERLESS_OCR_DPI=300
      - 'PAPERLESS_OCR_USER_ARGS={"invalidate_digital_signatures":true}'
      - PAPERLESS_TASK_WORKERS=1
      - PAPERLESS_THREADS_PER_WORKER=1

networks:
  default:
    name: lsio
    external: true
