services:
  curlbox:
    image: curlimages/curl:latest
    container_name: curlbox
    command: ["sleep", "infinity"]
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: lsio
    external: true
