version: "2.1"

services:

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "${DATA_PATH}/wireguard:/config"
      - "/lib/modules:/lib/modules"
    networks:
      default:
        ipv4_address: 172.19.0.50
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    env_file:
      - ../envs/base.env

networks:
  default:
    name: lsio
    external: true