version: "2.2"

services:

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PATH}/watchtower/config.json:/config.json
    env_file:
      - ../envs/base.env

networks:
  default:
    name: lsio
    external: true
