version: "2.2"

services:

  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: "portainer"
    command: "-H unix:///var/run/docker.sock"
    environment:
      - "VIRTUAL_HOST=portainer.chst.dev"
      - "VIRTUAL_PORT=9000"
    ports:
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DATA_PATH}/portainer:/data"
    restart: "always"
    env_file:
      - ../envs/base.env

  pgadmin:
    image: "dpage/pgadmin4"
    container_name: "pgadmin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    env_file:
      ../envs/db.env

networks:
  default:
    name: lsio
    external: true
